### PR TITLE
Change replaceWith calls to transitionTo to fix back button issues

### LINKED ISSUE #95: Back button is broken
If you navigate away from Stack#show and then click the back button, you are not returned to Stack#show.

### PR DESCRIPTION
**Pull request by bantic**
@mixonic, for you. I'm not sure why we had as many `replaceWith` calls as
we did. I've hand-tested for deleterious effects of making these changes
and have not found any.

fixes #95

### CODE REVIEW

**Comment by mixonic** [comment]
transitionTo makes a history entry. if you are redirected and click back, you often don't want to return to the redirect itself. Instead the redirect is mean to rewrite where you currently are. Obviously this isn't true 100% of the time, but I think in many of these cases it is true.

For instance the database index route. There is no reason I would want a click of the back button to return me to that route (which does nothing but redirect).

**Comment by bantic** [comment]
@mixonic if you change the `transitionTo` to a `replaceWith` in the database/index/route.js you get this behavior (for me, in Chrome):

  * Click "apps" tab
  * click "databases" tab
  * click a database
  * back button
  * end up erroneously on "apps" page

Changing to `transitionTo` fixes this for me.

Screencap:
db

**Comment by mixonic** [comment]
Ok. My understanding must be flawed? I would like to know what is actually happening here. I don't doubt these changes improved some specific behavior, I was wondering if the change was warranted in so many places.

I'll pull it down and figure out what is happening then report back.

**Comment by bantic** [comment]
let me know what you find, or if you want to pair. It doesn't fit my mental model of how `replaceWith` works, either.

**Comment by mixonic** [comment]
Let's review this in the AM.

**Pull request merged**
