### PR TITLE
Upgrade to ember 1.11.0-beta.5

### PR DESCRIPTION
**Pull request by bantic**
upgrade to [ember 1.11.0-beta.5](http://emberjs.com/blog/2015/02/07/ember-1-10-0-released.html)

### CODE REVIEW

**Comment by bantic** [comment]
I'm going to merge this after the build goes green.

**Comment by mixonic** [comment]
@bantic `tagName: ''` didn't work?

**Comment by bantic** [comment]
@mixonic It breaks the test with "Assertion Failed: You cannot access this.$() on a component with `tagName: ''` specified."

**Comment by mixonic** [comment]
That is unexpected. I wonder if that means an addon is reopening all components or something. We should still be able to use `tagName: ''`

**Comment by bantic** [comment]
@mixonic it comes from here: https://github.com/emberjs/ember.js/blob/06e41ad7ccd28558dd4e651aa070bc06f7757821/packages/ember-views/tests/views/view/jquery_test.js#L54

Ok to merge, or do you want to look into that?

**Comment by bantic** [comment]
Pending this upstream PR to change `moduleForModel`'s `render` callback:
https://github.com/switchfly/ember-test-helpers/pull/26

**Comment by mixonic** [comment]
@sandersonet we believe much of the back button funkiness was due to a bug in Ember 1.10. It is fixed in 1.11, and we will check how things improve with this patch.

**Pull request merged**
